/**
 * Swagger 
 * .
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apiteam@swagger.io
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface Alimentari { 
    data?: string;
    furnizor?: string;
    number?: number;
    auto?: string;
    sumaTotala?: number;
    // sumaFaraTVA?: number;
    // tva?: number;
    litri?: number;
}
